### ISSUE TITLE
Determine Cause of CAN Errors

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/frc-software-2022#164]
We recently added code to check for CAN errors using the TalonUtil class' checkError method. We are getting many errors even when the robot appears to be working fine. The error code is -3 which maps to CAN_MSG_NOT_FOUND.

This requires investigation. It is possible that these errors are being generated because we changed the CAN message period for some messages but other code is expecting the default period.

**Comment by admodi** [comment]
We not longer use the TalonUtil class, as we find canIssues using the CANDeviceFinder and CANDeviceid classes. I commented it out in the roboteer branch, but we should no longer need it.

**Comment by gcschmit** [comment]
not worth pursuing at the moment; closing
